# Generated by Django 3.1.7 on 2021-04-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacc_num', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('racc_num', models.IntegerField()),
                ('rname', models.CharField(max_length=100)),
                ('amt', models.IntegerField()),
            ],
        ),
    ]
